name: Build and release mod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build modpacker conatiner
        uses: docker/build-push-action@v6
        with:
          context: .
          file: modpack.dockerfile
          push: false
          tags: modpacker:latest

      - name: Build modpack
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd)/src":/src modpacker:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_result
          path: src/CloudSaveS3.mod.zip

      - name: Upload Artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src/CloudSaveS3.mod.zip
