name: Build and release mod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build modpack
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd)/src":/src ghcr.io/lyoko-jeremie/sugarcube-2-modloader-inserttools:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_result
          path: src/CloudSaveS3.mod.zip

      - name: Upload Artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src/CloudSaveS3.mod.zip
